#!/bin/sh
# Removes the out-of-source build/ directory plus any stray in-source
# CMake files (leftover from running `cmake .` directly in ad_src/), and
# the artifacts generated by the drivers at run time.
#
# NOTE: this also deletes optimizer output/ folders (the dated
# output/<date>_<experiment>/ dirs written by drag_opt_fd/drag_opt_ad).
# Those hold your saved optimization runs -- copy anything you want to
# keep out of the run directory before running this.
set -e
cd "$(dirname "$0")"

# build trees
rm -rf build buld
rm -rf CMakeCache.txt CMakeFiles Makefile cmake_install.cmake

# optimizer output folders (created in the directory the driver is run
# from, e.g. ad_src/ or ad_src/bezier/) and stray SPARTA temp surf files
rm -rf output bezier/output
rm -f tmp_surf_* bezier/tmp_surf_*

echo "ad_src cleaned."
